routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/', 'products');

Auth::routes();

Route::resource('products', 'ProductController');
Route::delete('images/{productImage}', 'ImageController@destroy')->name('images.destroy');

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    protected $fillable = ['name','description','price'];

    public function images()
    {
        return $this->hasMany(ProductImage::class);
    }

    public function mainImage()
    {
        return $this->hasOne(ProductImage::class)->where('is_default', 1);
    }
}

app/Models/ProductImage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Storage;

class ProductImage extends Model
{
    protected $fillable = ['product_id','is_default','path'];

    public function getUrlAttribute()
    {
        return Storage::url($this->path);
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use Notifiable, HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ImageController.php
<?php

namespace App\Http\Controllers;

use App\Models\ProductImage;
use Illuminate\Http\Request;

class ImageController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('role:admin');
    }
   
    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\ProductImage  $productImage
     * @return \Illuminate\Http\Response
     */
    public function destroy(ProductImage $productImage)
    {
        $productImage->delete();
        return response()->json([
            'message'=>'image deleted successful'
        ]);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Traits\FileTrait;
use App\Classes\StorageTree;
use Illuminate\Http\Request;
use App\Http\Requests\StoreProductRequest;
use App\Http\Requests\UpdateProductRequest;

class ProductController extends Controller
{
    use FileTrait;

    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('role:admin')->except('index', 'show');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = Product::with('mainImage')->latest()->get();
        return view('products.index', compact('products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('products.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StoreProductRequest $request)
    {
        $productData = $request->only(['name','description','price']);
        
        $product = Product::create($productData);

        $images = [];
        if ($request->has('main_image')) {
            $images[] = [
                'path' => $this->saveFile($request->main_image, StorageTree::PRODUCTS, $product->id),
                'is_default' => true
            ];
        }

        if ($request->has('images')) {
            foreach ($request->images as $image) {
                $images[] = [
                'path' => $this->saveFile($image, StorageTree::PRODUCTS, $product->id),
                ];
            }
        }

        $product->images()->createMany($images);
        return redirect(route('products.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {
        $product->load('images');
        return view('products.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        $product->load(['images' => function ($query) {
            $query->where('is_default', '0');
        } ]);
        return view('products.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateProductRequest $request, Product $product)
    {
        $productData = $request->only(['name','description','price']);
        $product->update($productData);
        
        $images = [];
        if ($request->has('main_image')) {
            $product->mainImage->delete();
            $images[] = [
                'path' => $this->saveFile($request->main_image, StorageTree::PRODUCTS, $product->id),
                'is_default' => true
            ];
        }
        
        if ($request->has('images')) {
            foreach ($request->images as $image) {
                $images[] = [
                'path' => $this->saveFile($image, StorageTree::PRODUCTS, $product->id),
                ];
            }
        }
        $product->images()->createMany($images);

        return redirect(route('products.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        $product->delete();
        return response()->json([
            'message' => 'deleted successful'
        ]);
    }
}

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Products Crud</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    Products Crud
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }}
                                </a>
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" >
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    @yield('script')
</body>
</html>

resources/views/products/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form action="{{route('products.store')}}" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" placeholder="name">
            @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="price">price</label>
            <input type="number" min="0" class="form-control" name="price" id="price" value="{{ old('price') }}" placeholder="price">
            @error('price')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="description">description</label>
            <textarea type="text" min="0" class="form-control" name="description"  id="description" placeholder="description">{{ old('description') }}</textarea>
            @error('description')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="main-image">product main image</label>
            <input type="file" class="form-control-file" id="main-image" name="main_image">
            @error('main_image')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="images">Product images</label>
            <input type="file" class="form-control-file" id="images" name="images[]" multiple>
            @error('images')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            @error('images.*')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

@endsection

resources/views/products/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <form action="{{route('products.update',$product->id)}}" method="POST" enctype="multipart/form-data">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="name">Name</label>
            <input type="text" class="form-control" id="name" name="name" placeholder="name" value="{{$product->name}}">
            @error('name')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="price">price</label>
            <input type="number" min="0" class="form-control" name="price" id="price" placeholder="price" value="{{$product->price}}">
            @error('price')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="description">description</label>
            <input type="text" min="0" class="form-control" name="description" id="description" value="{{$product->description}}" placeholder="description">
            @error('description')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="form-group">
            <label for="main-image">main-image</label>
            <input type="file" class="form-control-file" id="main-image" name="main_image">
            @error('main_image')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <div class="row">
            @foreach ($product->images as $image)
                <div class="col-4 single-image">
                    <img src="{{$image->url}}" style="max-height: 100%; max-width:100%; display:block" alt="">
                    <a href="{{route('images.destroy',$image->id)}}" class="btn btn-danger image-destroy">delete</a>
                </div>
            @endforeach
        </div>
        <div class="form-group">
            <label for="images">images</label>
            <input type="file" class="form-control-file" id="images" name="images[]" multiple>
            @error('images')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
            @error('images.*')
                <div class="alert alert-danger">{{ $message }}</div>
            @enderror
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

@endsection

@section('script')
<script>
    $(document).ready(()=>{

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $(document).on('click','.image-destroy',(e)=>{
            e.preventDefault();
            let selector = $(e.target) ;
            let url = selector.attr('href')
            let target = selector.closest('.single-image')
           
            destroyImage(url,target)
        });
        

    });

    function destroyImage(url,target)
    {
         $.ajax({
                method: "delete",
                url :url,
            })
            .done(function(response ) {
                target.remove()
            });
    }
</script>
    
@endsection

resources/views/products/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @auth
        @role('admin')
            <a href="{{route('products.create')}}" class="btn btn-dark">New Product</a>
        @endrole
    @endauth
    
    <div class="row " id="products-list">
        @forelse ($products as $product)
            <div class="col-lg-4 col-md-6 py-3 single-product">
                <h3 class="product-name">{{$product->name}}</h3>
                <p class="product-price">{{$product->price}}</p>
                <p class="product-description">{{$product->description}}</p>
                <div class="row">
                    <div class="col-4">
                        <a href="{{route('products.show',$product->id)}}" class="btn btn-primary product-show">show</a>
                    </div>
                    @auth
                        @role('admin')
                            <div class="col-4">
                                <a href="{{route('products.destroy',$product->id)}}" class="btn btn-danger product-destroy">delete</a>
                            </div>
                            <div class="col-4">
                                <a href="{{route('products.edit',$product->id)}}" class="btn btn-success product-edit">edit</a>
                            </div>
                        @endrole
                    @endauth
                </div>
            </div>
        @empty
            <div class="col-lg-4 col-md-6 py-3 single-product" style="display: none">
                <h3 class="product-name"></h3>
                <p class="product-price"></p>
                <p class="product-description"></p>
                <div class="row">
                    <div class="col-4">
                        <a href="" class="btn btn-primary product-show">show</a>
                    </div>
                    @auth
                        @role('admin')
                            <div class="col-4">
                                <a href="" class="btn btn-danger product-destroy">delete</a>
                            </div>
                            <div class="col-4">
                                <a href="" class="btn btn-success product-edit">edit</a>
                            </div>
                        @endrole
                    @endauth
                </div>
            </div>
        @endforelse
    </div>
</div>
@endsection
@section('script')
    <script src="{{asset('js/app.js')}}"></script>
<script>
    $(document).ready(()=>{

        // listen to new products
        subscribeToProducts()

        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        $(document).on('click','.product-destroy',(e)=>{
            e.preventDefault();
            let selector = $(e.target) ;
            let url = selector.attr('href')
            let target = selector.closest('.single-product')

            destroyProduct(url,target)
        });


    });

    function subscribeToProducts()
    {
        Echo.channel('products')
            .listen('.product.new', (e) => {
                console.log(e.product);
                appendProduct(e.product)
            });
    }


    function appendProduct(product)
    {
        // prepare new product links
        let showLink = "{{route('products.show','id')}}"
        let editLink = "{{route('products.edit','id')}}"
        showLink = showLink.replace("id", product.id);
        editLink = editLink.replace("id", product.id);

        // prepare new product div
        let cloned = $('.single-product:first').clone().show()
        cloned.find('.product-name').text(product.name)
        cloned.find('.product-price').text(product.price)
        cloned.find('.product-description').text(product.description)
        cloned.find('.product-show').attr('href',showLink)
        cloned.find('.product-edit').attr('href',editLink)
        cloned.find('.product-destroy').attr('href',showLink)
        $('#products-list').prepend(cloned);
    }

    function destroyProduct(url,target)
    {
         $.ajax({
                method: "delete",
                url :url,
            })
            .done(function(response ) {
                target.remove()
            });
    }
</script>

@endsection

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
        <h3>{{$product->name}}</h3>
        <p>{{$product->price}}</p>
        <p>{{$product->description}}</p>
        <div class="row">
            @foreach ($product->images as $image)
                <div class="col-4">
                    <img src="{{$image->url}}" style="max-height: 100%; max-width:100%" alt="">
                </div>
            @endforeach
        </div>
</div>
@endsection